### ISSUE TITLE
Mario clips through thin walls

### ISSUE THREAD

**Issue by SaviDaWavi** [Brawmario/libsm64-godot#7] opened 2023-09-24 05:01 UTC
In the Bob-omb Battlefield example, Mario clips one way through the fences. It seems to depend on which way the normals are facing, but if you have a thin object with collision Mario will clip through it even if you have normals facing out on both sides.

**Comment by Brawmario** [comment] 2023-09-24 21:34
Actually, from what I can tell, these meshes don't actually have normals on both sides, the culling mode on them is simply disabled. This isn't because the fences are "too thin", A thin cube mesh would still work properly. Because the meshes are sent to the libsm64 as triangles facing a specific way, "widthless" planes will only have collisions on one side. Maybe I should add a new parameter to the `SM64SurfacePropertiesComponent` node in order to allow for both side faces collision, since the current behavior is still pretty usefull for one-way surfaces. I'll have to think about a good way to export this to the API.

**Comment by SaviDaWavi** [comment] 2023-09-24 22:41
If you could add that parameter it would be great! I tested having a thin cube mesh and it seems to have the same issue. If you have two one way normals facing out it, it has issues and Mario tends to get stuck in the middle of the two shapes.

**Comment by Brawmario** [comment] 2023-09-25 00:26
Oh now that I've done some more testing I understand, it's not just a matter of (not) having multiple faces. I tried out having a 0.2 meter wide cube and it seems to work until this point (at the default SM64Global.scale), lower than that it kinda stops working.

In all honesty, as far as I can tell this is basically a core limitation of the SM64 engine (and not a code mistake on my part) and as such, my addon is thusly "working as intended", maybe it would be best to just avoid thin walls if you can help it. If you want to stop this from happening in your project you might want to do some custom physics on top of Mario, maybe by having a `StaticBody3D` move and collide alongside with the Mario node and then dynamically reposition Mario with the `SM64Mario.teleport` function as the Body collides. It may seem a bit silly but this addon is supposed to expose an 100% accurate simulation of the Super Mario 64 engine, bugs and all.

**Comment by SaviDaWavi** [comment] 2023-09-25 01:56
If you could add the double sided property it might help. I was just trying to replicate the fences from the sm64 because as of right now I am unsure how to go about it.

**Comment by Brawmario** [comment] 2023-09-25 02:27
Unfortunately I've found that double sided property only makes this worse, Mario will now clip no matter how wide it is. I even booted up SM64 to check out the original fences, I'm really not sure how they work exactly, I would have to dig into the decompilation project to seek how the fences work. Maybe it's a combination of planes with a specific Surface Property.

**Comment by Wall-E20** [comment] 2023-09-25 02:43
sometimes the actual model is different than the collisions in mario 64. fences have a triangular like collision

**Comment by Wall-E20** [comment] 2023-09-25 03:11
> sometimes the actual model is different than the collisions in mario 64. fences have a triangular like collision

![Polish_20230925_051018639.jpg](https://github.com/Brawmario/libsm64-godot/assets/107189660/a2bcd81b-c85e-4b98-b487-0d9df44fec56)
here the actual collision

**Comment by Brawmario** [comment] 2023-09-25 03:21
I figured the model wasn't the same, I did use a CC-BY-4.0 recreation of Bob Omb Battlefield, not the actual level extracted from the ROM. 

Thanks for the insight! This certainly explains how the fence collision works, it's a boxed wall with a triangular prism on the top. Where did you get this image?

I think I'll close this issue now @Savbyn , I feel like this is proof enough that the reported behavior is the expected one, hopefully now you can recreate the fence how you want. If you want to make the fence have a different collision to the actual model, you can instead make an "collision" mesh for the fence, add it to the `libsm64_static_surfaces` group and then simply make it invisible. I tried to make my addon be able to use the native Godot Collision Shapes but I'm having trouble figuring out how to break the shapes down to vertices the same way you can do to meshes, since that's the only way to pass the collision shapes to libsm64.

**Closed as completed by Brawmario** 2023-09-25 03:21 UTC

**Comment by Wall-E20** [comment] 2023-09-25 04:10
> I figured the model wasn't the same, I did use a CC-BY-4.0 recreation of Bob Omb Battlefield, not the actual level extracted from the ROM. 
> 
> Thanks for the insight! This certainly explains how the fence collision works, it's a boxed wall with a triangular prism on the top. Where did you get this image?
> 
> I think I'll close this issue now @Savbyn , I feel like this is proof enough that the reported behavior is the expected one, hopefully now you can recreate the fence how you want. If you want to make the fence have a different collision to the actual model, you can instead make an "collision" mesh for the fence, add it to the `libsm64_static_surfaces` group and then simply make it invisible. I tried to make my addon be able to use the native Godot Collision Shapes but I'm having trouble figuring out how to break the shapes down to vertices the same way you can do to meshes, since that's the only way to pass the collision shapes to libsm64.
> 
> 

image is from this video: [https://youtu.be/kRCjVLqjST4?si=-2eBDigqTt_b2bfL]()
the tool can be found on this video's description
[https://youtu.be/CLNSw11RQCQ?si=arOm7fp-8tV_gCz4]()
